### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by eholzbe**
Extended interpretation methods for observations of steady state

### CODE REVIEW

**Comment by philipperenard** [comment]
Very cool ! Thanks a lot for the contribution.

I had no time yet to run the code and test it in detail. I just saw some slight differences in the way you named the functions and how they are named elsewhere in hytool.

Normally the **fit** function is used only to fit the model. The figure that report the results is in the **rpt** function. I understand that it is more efficient to do the fit and report simultaneously and it makes sense to join the two things as you did. However, it may be confusing for the users if the nomenclature differs from one analytical solution to the next. 

Another thing that we need to do to integrate your solutions is to update the help and add your functions in the list of methods, this can be done in the **html** directory, the files **steady.html** for example contains the list of models for steady state. 

To generate the other individual help files, there are functions in the basic hytool directory: mkhtml, mkhelp or mkdemo, which generates automatically the html files. We could also run that.

What do you think ? Would it be possible to split the functions and be more consistent ? I could try to make this correction myself, but I am pretty busy at the moment with travels and conferences.

**Comment by eholzbe** [comment]
Thanks, it is not a big thing. I am using hytool for pumping tests and also in education. It is really a great tool! 

I tried to follow the hytool design using fit and rpt functions in my commit. However that finally seemed intricated, as the called functions with graphic and legends are constructed for the common unsteady case and not for the steady state. It is somehow artificial to adopt this procedure for the steady case. The derivatives would have to be suppressed for example, etc. I saw the design is not folowed in the original 'steady.m' method.  

Anyway, I think I managed to update the html-documentation so that it fits. I used the mkdemo and mkhtml files. The 'steady.html' is the only file that I changed manually. I added all html-files and graphics as another commit, so you can see them. 

I am using hytool now in a university course on 'Hydraulic Testing' in hydrogeology. It is a very nice way to teach this topic with all its variations to the students. However, the undergradients have difficulties learning MATLAB, so that last semester I had to construct a GUI for them to use hytool in the 'Hydraulic Testing' course. 

Best regards

**Comment by eholzbe** [comment]
Updated html-documentation

**Comment by philipperenard** [comment]
I finally took the time to check your code and merge it with hytool. Thanks a lot for the contribution.

**Pull request merged**
